-- The source view contains the complete authoritative month. Delta replaces
-- only that month in one transaction, so daily and monthly data are never added.

INSERT INTO TABLE {fact_cost_usage}
REPLACE WHERE billing_month = '{billing_month}'
WITH numbered AS (
  SELECT
    source.*,
    row_number() OVER (
      PARTITION BY _source_file
      ORDER BY ChargePeriodStart, ChargePeriodEnd, ResourceId, SkuId,
               ServiceName, BilledCost, EffectiveCost, ListCost
    ) AS gold_source_row_number
  FROM {source_month} AS source
), normalized AS (
  SELECT
    *,
    coalesce(nullif(trim(BillingAccountId), ''), 'Unknown') AS n_billing_account_id,
    coalesce(nullif(trim(SubAccountId), ''), 'Unknown') AS n_sub_account_id,
    coalesce(nullif(trim(x_BillingProfileId), ''), 'Unknown') AS n_billing_profile_id,
    coalesce(nullif(trim(ProviderName), ''), 'Unknown') AS n_provider_name,
    coalesce(nullif(trim(ResourceId), ''), 'Unknown') AS n_resource_id,
    coalesce(nullif(trim(ServiceName), ''), 'Unknown') AS n_service_name,
    coalesce(nullif(trim(ServiceCategory), ''), 'Unknown') AS n_service_category,
    coalesce(nullif(trim(x_PublisherId), ''), 'Unknown') AS n_publisher_id,
    coalesce(nullif(trim(PublisherName), ''), 'Unknown') AS n_publisher_name,
    coalesce(nullif(trim(x_PublisherCategory), ''), 'Unknown') AS n_publisher_category,
    coalesce(nullif(trim(x_ResellerId), ''), 'Unknown') AS n_reseller_id,
    coalesce(nullif(trim(x_ResellerName), ''), 'Unknown') AS n_reseller_name,
    coalesce(nullif(trim(SkuId), ''), 'Unknown') AS n_sku_id,
    coalesce(nullif(trim(SkuPriceId), ''), 'Unknown') AS n_sku_price_id,
    coalesce(x_SkuDescription, '') AS n_sku_description,
    coalesce(x_SkuDetails, '') AS n_sku_details,
    coalesce(nullif(trim(x_SkuMeterId), ''), 'Unknown') AS n_meter_id,
    coalesce(nullif(trim(x_SkuMeterName), ''), 'Unknown') AS n_meter_name,
    coalesce(nullif(trim(x_SkuMeterCategory), ''), 'Unknown') AS n_meter_category,
    coalesce(nullif(trim(x_SkuMeterSubcategory), ''), 'Unknown') AS n_meter_subcategory,
    coalesce(nullif(trim(x_SkuOfferId), ''), 'Unknown') AS n_offer_id,
    coalesce(nullif(trim(x_SkuOrderId), ''), 'Unknown') AS n_order_id,
    coalesce(nullif(trim(x_SkuOrderName), ''), 'Unknown') AS n_order_name,
    coalesce(nullif(trim(x_SkuPartNumber), ''), 'Unknown') AS n_part_number,
    coalesce(nullif(trim(x_SkuRegion), ''), 'Unknown') AS n_sku_region,
    coalesce(nullif(trim(x_SkuServiceFamily), ''), 'Unknown') AS n_sku_service_family,
    coalesce(nullif(trim(x_SkuTerm), ''), 'Unknown') AS n_sku_term,
    coalesce(nullif(trim(x_SkuTier), ''), 'Unknown') AS n_sku_tier,
    coalesce(nullif(trim(Region), ''), 'Unknown') AS n_region,
    coalesce(nullif(trim(CommitmentDiscountId), ''), 'Unknown') AS n_commitment_id,
    coalesce(nullif(trim(CommitmentDiscountName), ''), 'Unknown') AS n_commitment_name,
    coalesce(nullif(trim(CommitmentDiscountCategory), ''), 'Unknown') AS n_commitment_category,
    coalesce(nullif(trim(CommitmentDiscountType), ''), 'Unknown') AS n_commitment_type,
    coalesce(nullif(trim(PricingCategory), ''), 'Unknown') AS n_pricing_category,
    coalesce(nullif(trim(x_PricingSubcategory), ''), 'Unknown') AS n_pricing_subcategory,
    coalesce(nullif(trim(PricingUnit), ''), 'Unknown') AS n_pricing_unit,
    coalesce(nullif(trim(x_PricingUnitDescription), ''), 'Unknown') AS n_pricing_unit_description,
    coalesce(nullif(trim(x_PricingCurrency), ''), nullif(trim(BillingCurrency), ''), 'Unknown') AS n_pricing_currency,
    coalesce(nullif(trim(ChargeCategory), ''), 'Unknown') AS n_charge_category,
    coalesce(nullif(trim(ChargeFrequency), ''), 'Unknown') AS n_charge_frequency
  FROM numbered
)
SELECT
  sha2(concat_ws('||', 'fact', coalesce(_source_file, 'Unknown'),
    CAST(gold_source_row_number AS STRING)), 256) AS cost_usage_sk,
  sha2(concat_ws('||', 'charge', coalesce(_source_file, 'Unknown'),
    CAST(gold_source_row_number AS STRING)), 256) AS charge_id,
  billing_month,
  sha2(concat_ws('||', 'billing_scope', n_billing_account_id,
    n_sub_account_id, n_billing_profile_id), 256) AS billing_scope_sk,
  sha2(concat_ws('||', 'resource', n_provider_name, n_resource_id), 256) AS resource_sk,
  sha2(concat_ws('||', 'service', n_service_name, n_service_category,
    n_provider_name, n_publisher_id, n_publisher_name,
    n_publisher_category, n_reseller_id, n_reseller_name), 256) AS service_sk,
  sha2(concat_ws('||', 'sku', n_sku_id, n_sku_price_id, n_sku_description,
    n_sku_details, n_meter_id, n_meter_name, n_meter_category,
    n_meter_subcategory, n_offer_id, n_order_id, n_order_name,
    n_part_number, n_sku_region, n_sku_service_family, n_sku_term,
    n_sku_tier, coalesce(CAST(x_SkuIsCreditEligible AS STRING), 'Unknown')), 256) AS sku_sk,
  sha2(concat_ws('||', 'location', n_region, 'Unknown', n_sku_region), 256) AS location_sk,
  sha2(concat_ws('||', 'pricing', n_pricing_category,
    n_pricing_subcategory, n_pricing_unit, n_pricing_unit_description,
    n_pricing_currency, coalesce(CAST(x_PartnerCreditApplied AS STRING), 'Unknown')), 256) AS pricing_sk,
  sha2(concat_ws('||', 'commitment', n_commitment_id, n_commitment_name,
    n_commitment_category, n_commitment_type), 256) AS commitment_sk,
  sha2(concat_ws('||', 'charge_type', n_charge_category, 'Unknown',
    n_charge_frequency), 256) AS charge_type_sk,
  CAST(date_format(to_date(BillingPeriodStart), 'yyyyMMdd') AS BIGINT) AS billing_period_start_date_sk,
  CAST(date_format(to_date(BillingPeriodEnd), 'yyyyMMdd') AS BIGINT) AS billing_period_end_date_sk,
  CAST(date_format(to_date(ChargePeriodStart), 'yyyyMMdd') AS BIGINT) AS charge_period_start_date_sk,
  CAST(date_format(to_date(ChargePeriodEnd), 'yyyyMMdd') AS BIGINT) AS charge_period_end_date_sk,
  CAST(date_format(to_date(x_ServicePeriodStart), 'yyyyMMdd') AS BIGINT) AS service_period_start_date_sk,
  CAST(date_format(to_date(x_ServicePeriodEnd), 'yyyyMMdd') AS BIGINT) AS service_period_end_date_sk,
  CAST(date_format(to_date(x_BillingExchangeRateDate), 'yyyyMMdd') AS BIGINT) AS exchange_rate_date_sk,
  BilledCost AS billed_cost,
  EffectiveCost AS effective_cost,
  ListCost AS list_cost,
  ListUnitPrice AS list_unit_price,
  x_BilledCostInUsd AS billed_cost_usd,
  x_EffectiveCostInUsd AS effective_cost_usd,
  CASE WHEN PricingCategory = 'On-Demand' THEN ListCost END AS on_demand_cost,
  CASE WHEN PricingCategory = 'On-Demand' THEN x_BilledCostInUsd END AS on_demand_cost_usd,
  x_BilledUnitPrice AS billed_unit_price,
  x_EffectiveUnitPrice AS effective_unit_price,
  CASE WHEN PricingCategory = 'On-Demand' THEN ListUnitPrice END AS on_demand_unit_price,
  ConsumedQuantity AS usage_quantity,
  coalesce(nullif(trim(ConsumedUnit), ''), 'Unknown') AS usage_unit,
  PricingQuantity AS pricing_quantity,
  x_PricingBlockSize AS pricing_block_size,
  x_PartnerCreditRate AS partner_credit_rate,
  x_BillingExchangeRate AS billing_exchange_rate,
  coalesce(ChargeDescription, '') AS charge_description,
  BillingCurrency AS billing_currency,
  _ingested_at AS ingestion_timestamp,
  ProviderName AS source_system,
  '{focus_version}' AS focus_version,
  _contract_version AS contract_version,
  _ingestion_run_id AS batch_id
FROM normalized;
